### ISSUE TITLE
Not an Issue, Just a Thank You

### ISSUE THREAD

**Issue by Day36512** [NetherstormX/NetherBot#1]
Hey Man!

Didn't know how to properly get in touch with you but wanted to say thank you for producing this addon! You did a fantastic job!

If anyone else uses Trickerer's NPCbots, I highly reccomend you download this addon. Helps make things super simplified and frankly the addon design is just really good, very intuitive. 

Have a fantastic week ahead!

**Comment by Netherstack** [comment]
Yow!, It means a lot to me to hear that you found it helpful/usefull, thnx for taking the time to review and and give this great feedback. You made my day!.

p.s.: sorry for not seeing/replying this earlier.

**Comment by NetherstormX** [comment]
Yow!, It means a lot to me to hear that you found it helpful/usefull, thnx for taking the time to review and and give this great feedback. You made my day!.

p.s.: sorry for not seeing/replying this earlier.
